name: Ruff Lint (changed files only)

on:
  push:
    paths: ["**/*.py", ".github/workflows/ci.yaml"]
  pull_request:
    paths: ["**/*.py", ".github/workflows/ci.yaml"]

permissions:
  # 只读就够：不用自动 commit
  contents: read
  pull-requests: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      # ① 拉代码（完整历史用于 diff）
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ② 取出本次改动的 *.py 列表
      - name: Get changed *.py files
        id: cf
        uses: tj-actions/changed-files@v45
        with:
          files: "**/*.py"

      # ③ Ruff 检查（不自动修复）
      - name: Ruff check (changed files)
        if: steps.cf.outputs.any_changed == 'true'
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ${{ steps.cf.outputs.all_changed_files }}"

      # ④ 若本次没有 Python 变动则跳过
      - name: Skip – no Python changes
        if: steps.cf.outputs.any_changed == 'false'
        run: echo "No Python files changed – skipping Ruff."
